In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Datasets/raw_data-all_rental_listings(rent.com.bd).csv')
df.head(5)

,url,title,property type,property size,parking,lift,floor,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000 Sq Ft,01,01,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500 Sq Ft,02,01,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial space rent in Dhaka | 225+ Spaces f...,20000 Sq. Ft. (Per floor 4000 Sq. Ft.),05 car parking,03,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250 Sq Ft,01,02,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300 Sq Ft,02,02,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [3]:
#Check for duplicated rows
df.duplicated().any()

False

In [4]:
# check for null rows
df.isnull().any()

url                           False
title                         False
property type                 False
property size                  True
parking                        True
lift                           True
floor                          True
price                          True
service_charge                 True
year built                     True
building registration type     True
preferred tennant              True
interior                       True
garage size                    True
front road size                True
common area                    True
bedrooms                       True
bathrooms                      True
location                      False
country                       False
dtype: bool

In [5]:
# Extract property size from title for the rows
# that have empty values on the property size column

df.loc[df['property size'].isnull(),'property size']=df[df['property size'].isnull()]["title"].str.extract('(\d{3,4})')[0]

In [6]:
#Standardize the 'property type' column 
df.loc[df['property type'].str.contains('Residential'),'property type']='Residential Apartment'
df.loc[df['property type'].str.contains('Commercial'),'property type']='Commercial Space'
df.loc[df['property type'].str.contains('Furnished'),'property type']='Residential Apartment'
df.head(5)

,url,title,property type,property size,parking,lift,floor,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000 Sq Ft,01,01,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500 Sq Ft,02,01,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial Space,20000 Sq. Ft. (Per floor 4000 Sq. Ft.),05 car parking,03,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250 Sq Ft,01,02,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300 Sq Ft,02,02,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [7]:
#Remove unwanted characters and substrings from 'property size' column
df['property size']=df['property size'].str.replace('.','')
df['property size']=df['property size'].str.split('Sq Ft').str[0]
df=df.rename(columns={'property size':'property size(Sq Ft)'})
df.head(5)

,url,title,property type,property size(Sq Ft),parking,lift,floor,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000,01,01,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500,02,01,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial Space,20000,05 car parking,03,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250,01,02,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300,02,02,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [8]:
# Standardize parking spots column  
df['parking']=df['parking'].str.strip('ÂCcar Pparking')
df=df.rename(columns={'parking':'parking spots'})
#df.head(50)

In [9]:
# Remove null values and unwanted strings in lift column
df['lift']=df['lift'].str.replace('available','')
df['lift']=df['lift'].str.replace('Available','')

In [10]:
df.loc[df['lift'].isnull(),'lift']=df[df['lift'].isnull()].fillna(0)
df.head(5)

,url,title,property type,property size(Sq Ft),parking spots,lift,floor,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000,01,01,3rd Floor Available,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500,02,01,6th-7th floor (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial Space,20000,05,03,11th-15th floor available,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250,01,02,7th Floor Available,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300,02,02,5th floor,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [11]:
# Clean the floor column and rename it
df['floor']=df['floor'].str.replace('Individual','Singular')
df['floor']=df['floor'].str.replace('Ground','G')
df['floor']=df['floor'].str.replace('–','&')
df['floor']=df['floor'].str.replace('available','')
df['floor']=df['floor'].str.replace('Available','')
df['floor']=df['floor'].str.replace('floor','')
df['floor']=df['floor'].str.replace('Floor','')
df['floor']=df['floor'].str.replace('st','')
df['floor']=df['floor'].str.replace('nd','')
df['floor']=df['floor'].str.replace('rd','')
df['floor']=df['floor'].str.replace('th','')
df=df.rename(columns={'floor':'floor available'})

In [12]:
df.head(5)

,url,title,property type,property size(Sq Ft),parking spots,lift,floor available,price,service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000,01,01,3,"BDT 80,000/-","BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500,02,01,6-7 (Duplex),"BDT 220,000/-","BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial Space,20000,05,03,11-15,"BDT 29,00,000/- (BDT 145/- per Sq Ft)","BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250,01,02,7,"BDT 100,000/-","BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300,02,02,5,"BDT 220,000/-","BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [13]:
# Clean price column and remove unwanted substrings
df['price']=df['price'].str.split('BDT').str[1]
df['price']=df['price'].str.split('/').str[0]
df['price']=df['price'].str.replace(',','')
df['price'] = df['price'].str.split(n=2).str[:2].str.join(' ')

In [14]:
# Remove null rows in price column
df = df[df['price'].notna()]

In [15]:
# convert values with 'Cr' into full valued strings
priceCR=df.loc[df['price'].str.contains(' Cr'),'price']
priceCR=priceCR.str.replace('Cr.','Cr', regex=True)
priceCR=priceCR.str.replace('cr.','Cr', regex=True)
priceCR=priceCR.apply(lambda x:str( float(x.replace(' Cr', '')) * 10000000))
df.loc[df['price'].str.contains(' Cr'),'price']=priceCR

In [16]:
# convert values with 'Lac' into full valued strings
priceLac=df.loc[df['price'].str.contains(' Lac'),'price']
priceLac=priceLac.apply(lambda x:str( float(x.replace(' Lac', '')) * 100000))
df.loc[df['price'].str.contains(' Lac'),'price']=priceLac

In [17]:
# Convert the price column string values into integer values
df['price']=df['price'].str.extract('(\d+)')
df['price']=df['price'].astype(int)
df=df.rename(columns={'price':'price(BDT)'})

In [18]:
df.head(5)

,url,title,property type,property size(Sq Ft),parking spots,lift,floor available,price(BDT),service_charge,year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000,01,01,3,80000,"BDT 8,500/-",2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500,02,01,6-7 (Duplex),220000,"BDT 17,000/-",2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial Space,20000,05,03,11-15,2900000,"BDT 300,000/- (BDT 15/- per Sq Ft)",2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250,01,02,7,100000,"BDT 15,000/-",2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300,02,02,5,220000,"BDT 25,000/-",2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [19]:
# Remove unwanted substrings and standardize service_charge column
df['service_charge']=df['service_charge'].str.replace('N/A','')
df['service_charge']=df['service_charge'].str.replace('BDT','')
df['service_charge']=df['service_charge'].str.split('/').str[0]
df['service_charge']=df['service_charge'].str.replace(',','')
df['service_charge']=df['service_charge'].str.replace('.','')
df['service_charge']=df['service_charge'].replace([' Not fixed yet',' Not Fixed Yet',' Not Fixed yet'],'Not fixed yet')
df['service_charge']=df['service_charge'].replace(' At Actual','At Actual')

changeWords=['Including',' Including',' Including Rent',' Including with monthly rent',' Included with monthly rent',' Including With Rent',' Including with rent']
df.loc[df['service_charge'].isin(changeWords),'service_charge']="Including with rent"

df['service_charge']=df['service_charge'].fillna(0)


df=df.rename(columns={'service_charge':'service charge(BDT)'})

In [20]:
df.head(5)

,url,title,property type,property size(Sq Ft),parking spots,lift,floor available,price(BDT),service charge(BDT),year built,building registration type,preferred tennant,interior,garage size,front road size,common area,bedrooms,bathrooms,location,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000,01,01,3,80000,8500,2010.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,16 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Banani, Dhaka 1213",Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500,02,01,6-7 (Duplex),220000,17000,2012.0,Residential,Foreigner,Semi-Furnished,240 Sq. Ft.,12 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial Space,20000,05,03,11-15,2900000,300000,2023.0,Commercial,Corporate Office or MNC Office,Un-Furnished,600 Sq Ft.,50 Ft.,1250 Sq Ft,NaN,NaN,"Gulshan, Dhaka 1212",Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250,01,02,7,100000,15000,2017.0,Residential,Foreigner,Un-Furnished,120 Sq. Ft.,24 Ft.,180 Sq Ft,03 Bedrooms,03 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300,02,02,5,220000,25000,2010.0,Residential,Foreigner,Un-Furnished,240 Sq. Ft.,16 Ft.,250 Sq Ft,04 Bedrooms,04 Bathrooms,"Gulshan, Dhaka 1212",Bangladesh

In [21]:
# reduce multiple aliases of the same type of record to one record for preferred tennant column
df['preferred tennant'].unique()

array([' Foreigner', 'Corporate Office or MNC Office',
       ' Corporate Office or MNC Offices',
       ' Corporate Office or Restaurant', ' Restaurant',
       ' Corporate or MNC Office', 'Corporate Office or MNC Offices.',
       ' Corporate Office or MNC Offices.', ' Corporate Office',
       ' Bank Space', ' Foreigner or Local', ' Foreign Companies', nan,
       ' Corporate Office or Small Office', ' Family',
       ' Corporate Office or Small Offices', ' Corporate Office or MNC',
       ' Corporate Office, MNC', ' Retail Brands & Foreign Franchise',
       ' Restaurant Brand', ' Corporate Office or MNC/ Restaurant'],
      dtype=object)

In [22]:
df['preferred tennant']=df['preferred tennant'].replace([' Corporate Office or MNC Offices',' Corporate or MNC Office','Corporate Office or MNC Offices.',' Corporate Office or MNC Offices.',' Corporate Office or MNC',' Corporate Office, MNC',' Corporate Office or MNC/ Restaurant'],'Corporate Office or MNC Office')
df['preferred tennant']=df['preferred tennant'].replace([' Corporate Office or Small Offices',' Corporate Office or Small Office'],'Corporate Office or Small Office')
df['preferred tennant']=df['preferred tennant'].replace(' Restaurant Brand',' Restaurant')
df['preferred tennant'].unique()

array([' Foreigner', 'Corporate Office or MNC Office',
       ' Corporate Office or Restaurant', ' Restaurant',
       ' Corporate Office', ' Bank Space', ' Foreigner or Local',
       ' Foreign Companies', nan, 'Corporate Office or Small Office',
       ' Family', ' Retail Brands & Foreign Franchise'], dtype=object)

In [23]:
# reduce multiple aliases of the same type of record to one record for interior column
sorted(df['interior'].unique())

[' Full Furnished',
 ' Full-Furnished',
 ' Fully Furnished',
 ' Fully-Furnished',
 ' Furnished',
 ' Non-Furnished',
 ' Semi-Furnished',
 ' Semi-Unfurnished',
 ' Semi-furnished',
 ' Un-Furnished',
 ' UnFurnished',
 ' Unfurnished',
 'Full-Furnished',
 'Fully-Furnished',
 'Furnished',
 'Semi ',
 'Semi-Furnished',
 'Un',
 'Un ',
 'Un- Furnished',
 'Un-Furnished',
 'Un-furnished']

In [24]:
df['interior']=df['interior'].replace([' Full Furnished',
 ' Full-Furnished',
 ' Fully Furnished',
 ' Fully-Furnished',
 ' Furnished','Full-Furnished',
 'Fully-Furnished','Furnished'],'Full-Furnished')

df['interior']=df['interior'].replace([' Semi-Furnished',
 ' Semi-Unfurnished',
 ' Semi-furnished','Semi ',
 'Semi-Furnished'],'Semi-Furnished')

df['interior']=df['interior'].replace([' Non-Furnished',' Un-Furnished',
 ' UnFurnished',
 ' Unfurnished','Un',
 'Un ',
 'Un- Furnished',
 'Un-Furnished',
 'Un-furnished'],'Un-Furnished')

sorted(df['interior'].unique())

['Full-Furnished', 'Semi-Furnished', 'Un-Furnished']

In [25]:
# Change year built column to int data
df['year built']=df['year built'].astype(int)

In [26]:
#Remove unwanted characters from garage size, front road size, common area columns
df['garage size']=df['garage size'].str.replace('.','')
df['garage size']=df['garage size'].str.replace('Sq Ft','')
df['garage size']=df['garage size'].str.replace(' Sq Ft','')
df['garage size']=df['garage size'].str.replace(' sq ft','')
df=df.rename(columns={'garage size':'garage size(Sq Ft)'})

df['front road size']=df['front road size'].str.replace('.','')
df['front road size']=df['front road size'].str.replace(' Ft','')
df['front road size']=df['front road size'].str.replace('Ft','')
df=df.rename(columns={'front road size':'front road size(Ft)'})

df['common area']=df['common area'].str.replace('.','')
df['common area']=df['common area'].str.replace('.','')
df['common area']=df['common area'].str.replace(' Sq Ft','')

df=df.rename(columns={'common area':'common area(Sq Ft)'})

In [27]:
#Remove unwanted characters from bedrooms column

df['bedrooms']=df['bedrooms'].str.extract('(\d+)').astype(float)
df['bedrooms']=df['bedrooms'].fillna(0)

In [28]:
#Remove unwanted characters from bathrooms column

df['bathrooms']=df['bathrooms'].str.extract('(\d+)').astype(float)
df['bathrooms']=df['bathrooms'].fillna(0)

In [29]:
df=df.reset_index(drop=True)

In [30]:
# Create new column postal code
df['postal code']=df['location'].str.extract('(\d{4})')

In [31]:
# standardize the location column
sorted(df['location'].unique())

['Banani',
 'Banani , Dhaka',
 'Banani 11, Dhaka',
 'Banani 11, Dhaka 1212',
 'Banani 12, Dhaka 1212',
 'Banani Dhaka 1213',
 'Banani block c',
 'Banani block k',
 'Banani, Dhaka',
 'Banani, Dhaka 1212',
 'Banani, Dhaka 1213',
 'Banani, Dhaka,',
 'Banani, Dhaka, Dhaka Metropolitan, Dhaka District, Dhaka Division, 1213, Bangladesh',
 'Baridhara Diplomatic Zone, 1212',
 'Baridhara Diplomatic Zone, Dhaka',
 'Baridhara Diplomatic Zone, Dhaka 1212',
 'Baridhara Diplomatic Zone, Dhaka, 1212',
 'Baridhara Diplomatic Zone, Dhaka- 1212',
 'Baridhara Diplomatic Zone, Dhaka-1212, Bangladesh',
 'Baridhara Diplomatic Zone, Gulshan',
 'Baridhara Diplomatic Zone,1212',
 'Baridhara Diplomatic Zone. Dhaka 1212',
 'Baridhara, Dhaka',
 'Baridhara, Dhaka 1212',
 'Baridhara, Gulshan, Dhaka, Chanpara Bazar, Dhaka District, Dhaka Division, 1230, Bangladesh',
 'Gulshan',
 'Gulshan , Dhaka',
 'Gulshan 1, Dhaka',
 'Gulshan 1, Dhaka 1212',
 'Gulshan 1, Dhaka, Dhaka District, Dhaka Division, 1212, Bangladesh',
 'Gulshan 2',
 'Gulshan 2 Circle, Dhaka 1212',
 'Gulshan 2,',
 'Gulshan 2, Dhaka',
 'Gulshan 2, Dhaka 1212',
 'Gulshan 2, Dhaka, Bangladesh',
 'Gulshan Avenue',
 'Gulshan Avenue, Dhaka 1212',
 'Gulshan Avenue, Gulshan',
 'Gulshan North, Dhaka 1212',
 'Gulshan, Dhaka',
 'Gulshan, Dhaka 1212',
 'Gulshan, Dhaka, 1212',
 'Gulshan, Dhaka, Chanpara Bazar, Dhaka District, Dhaka Division, 1230, Bangladesh',
 'Gulshan, Dhaka-1212',
 'Gulshan, road 114',
 'Gulswhan Avenue, Dhaka 12123',
 'Kemal Ataturk Avenue, Dhaka 1213',
 'Kemal Ataturk Avenue, Gulshan 2, Dhaka 1212',
 'Kemal Ataturk, Banani,1213',
 'North Banani, Dhaka',
 'North Gulshan 1, Dhaka 1212',
 'North Gulshan, Dhaka 1212',
 'North Gulshan, Dhaka- 1212',
 'Tejgaon, Dhaka 1208',
 'banani']

In [32]:

df['location'] = df['location'].replace(['Banani',
                                         'Banani , Dhaka',
                                         'Banani Dhaka 1213',
                                         'Banani, Dhaka',
                                         'Banani, Dhaka 1212',
                                         'Banani, Dhaka 1213',
                                         'Banani, Dhaka,',
                                         'Banani, Dhaka, Dhaka Metropolitan, Dhaka District, Dhaka Division, 1213, Bangladesh',
                                         'banani',
                                         'North Banani, Dhaka'], 'Banani')

df['location'] = df['location'].replace(['Baridhara Diplomatic Zone, 1212',
                                         'Baridhara Diplomatic Zone, Dhaka',
                                         'Baridhara Diplomatic Zone, Dhaka 1212',
                                         'Baridhara Diplomatic Zone, Dhaka, 1212',
                                         'Baridhara Diplomatic Zone, Dhaka- 1212',
                                         'Baridhara Diplomatic Zone, Dhaka-1212, Bangladesh',
                                         'Baridhara Diplomatic Zone, Gulshan',
                                         'Baridhara Diplomatic Zone,1212',
                                         'Baridhara Diplomatic Zone. Dhaka 1212',
                                         'Baridhara, Dhaka',
                                         'Baridhara, Dhaka 1212',
                                         'Baridhara, Gulshan, Dhaka, Chanpara Bazar, Dhaka District, Dhaka Division, 1230, Bangladesh'], 'Baridhara')

df['location'] = df['location'].str.replace('Banani 11, Dhaka', 'Banani 11')
df['location'] = df['location'].str.replace('Banani 11, Dhaka 1212', 'Banani 11')

df['location'] = df['location'].replace('Banani 12, Dhaka 1212', 'Banani 12')

df['location'] = df['location'].replace(['Gulshan',
                                         'Gulshan , Dhaka',
                                         'Gulshan, Dhaka',
                                         'Gulshan, Dhaka 1212',
                                         'Gulshan, Dhaka, 1212',
                                         'Gulshan, Dhaka, Chanpara Bazar, Dhaka District, Dhaka Division, 1230, Bangladesh',
                                         'Gulshan, Dhaka-1212',
                                         'Gulshan, road 114'], 'Gulshan')

df['location'] = df['location'].replace(['Gulshan 1, Dhaka',
                                         'Gulshan 1, Dhaka 1212',
                                         'Gulshan 1, Dhaka, Dhaka District, Dhaka Division, 1212, Bangladesh'], 'Gulshan 1')

df['location'] = df['location'].replace(['Gulshan 2',
                                         'Gulshan 2 Circle, Dhaka 1212',
                                         'Gulshan 2,',
                                         'Gulshan 2, Dhaka',
                                         'Gulshan 2, Dhaka 1212',
                                         'Gulshan 2, Dhaka, Bangladesh'], 'Gulshan 2')

df['location'] = df['location'].replace(['Gulshan Avenue',
                                         'Gulshan Avenue, Dhaka 1212',
                                         'Gulshan Avenue, Gulshan',
                                         'Gulswhan Avenue, Dhaka 12123'], 'Gulshan Avenue')

df['location'] = df['location'].replace(['North Gulshan 1, Dhaka 1212',
                                         'North Gulshan, Dhaka 1212',
                                         'North Gulshan, Dhaka- 1212',
                                         'Gulshan North, Dhaka 1212'], 'Gulshan North')

df['location'] = df['location'].replace(['Kemal Ataturk Avenue, Dhaka 1213',
                                         'Kemal Ataturk Avenue, Gulshan 2, Dhaka 1212',
                                         'Kemal Ataturk, Banani,1213'], 'Kemal Ataturk Avenue')

df['location'] = df['location'].replace('Tejgaon, Dhaka 1208', 'Tejgaon')

df['location'].unique()

array(['Banani', 'Gulshan', 'Baridhara', 'Gulshan Avenue', 'Gulshan 1',
       'Tejgaon', 'Gulshan 2', 'Kemal Ataturk Avenue', 'Banani block k',
       'Banani block c', 'Gulshan North', 'Banani 12', 'Banani 11 1212',
       'Banani 11'], dtype=object)

In [33]:
df['division']='Dhaka'

In [34]:
# Rearrange the columns
df=df[['url',
      'title','property type',
       'property size(Sq Ft)', 
       'parking spots',
       'lift',
       'floor available', 
       'price(BDT)',
       'service charge(BDT)',
       'year built', 
       'building registration type',
       'preferred tennant',
       'interior', 
       'garage size(Sq Ft)', 
       'front road size(Ft)', 
       'common area(Sq Ft)', 
       'bedrooms',
       'bathrooms', 
       'location',
       'postal code', 
       'division',
       'country']]

In [35]:
df.head(5)

,url,title,property type,property size(Sq Ft),parking spots,lift,floor available,price(BDT),service charge(BDT),year built,...,interior,garage size(Sq Ft),front road size(Ft),common area(Sq Ft),bedrooms,bathrooms,location,postal code,division,country
0,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2000 Sq Ft Is Up...,Residential Apartment,2000,01,01,3,80000,8500,2010,...,Un-Furnished,120,16,180,3.0,3.0,Banani,1213,Dhaka,Bangladesh
1,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4500 Sq Ft Is Up...,Residential Apartment,4500,02,01,6-7 (Duplex),220000,17000,2012,...,Semi-Furnished,240,12,250,4.0,4.0,Gulshan,1212,Dhaka,Bangladesh
2,https://rents.com.bd/property/brand-new-and-ta...,Brand New And Tastefully Designed This 20000 S...,Commercial Space,20000,05,03,11-15,2900000,300000,2023,...,Un-Furnished,600,50,1250,0.0,0.0,Gulshan,1212,Dhaka,Bangladesh
3,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 2250 Sq Ft Is Up...,Residential Apartment,2250,01,02,7,100000,15000,2017,...,Un-Furnished,120,24,180,3.0,3.0,Gulshan,1212,Dhaka,Bangladesh
4,https://rents.com.bd/property/a-modern-well-pl...,A Modern Well-planned Flat Of 4300 Sq Ft Is Up...,Residential Apartment,4300,02,02,5,220000,25000,2010,...,Un-Furnished,240,16,250,4.0,4.0,Gulshan,1212,Dhaka,Bangladesh

In [36]:
df.to_csv('Rental listings final.csv', index=False)